### ISSUE TITLE
/etc/init.d/mydlp restart does not work

### ISSUE THREAD

**Issue by bogus** [mydlp/mydlp#10]
It prints 

medra@ubuntu:~$ sudo /etc/init.d/mydlp restart
- Stopping MyDLP mydlp
  ...done.
- Stopping MyDLP Python Backend mydlp
  ...done.
- Stopping MyDLP Java Backend mydlp
  ...done.
- Starting MyDLP Java Backend mydlp
  ...done.
- Starting MyDLP Python Backend mydlp
  ...done.
- Starting MyDLP mydlp
  ...done.

However open ports are:

medra@ubuntu:~$ sudo netstat -pltn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:443             0.0.0.0:\*               LISTEN      2115/apache2  
tcp        0      0 0.0.0.0:9090            0.0.0.0:\*               LISTEN      1633/python  
tcp        0      0 127.0.0.1:3306          0.0.0.0:\*               LISTEN      1920/mysqld  
tcp        0      0 0.0.0.0:80              0.0.0.0:\*               LISTEN      2115/apache2  
tcp        0      0 0.0.0.0:4369            0.0.0.0:\*               LISTEN      833/epmd  
tcp        0      0 0.0.0.0:22              0.0.0.0:\*               LISTEN      1739/sshd  
tcp        0      0 127.0.0.1:631           0.0.0.0:\*               LISTEN      1632/cupsd  
tcp6       0      0 :::9000                 :::\*                    LISTEN      2195/eclipse  
tcp6       0      0 :::10000                :::\*                    LISTEN      2195/eclipse  
tcp6       0      0 :::22                   :::\*                    LISTEN      1739/sshd  
tcp6       0      0 ::1:631                 :::\*                    LISTEN      1632/cupsd

**Comment by hkerem** [comment]
unable to reproduce.
