### ISSUE TITLE
Log for content blocking

### ISSUE THREAD

**Issue by bogus** [mydlp/mydlp#6]
Currently in log file, it writes Files: "filename". It should write Files: "content" for content

**Comment by bogus** [comment]
Also, protocol have to be written

**Comment by hkerem** [comment]
A log line now likes this;

ACL: 2010-07-19 17:36:19 -> PROTOCOL: http , FROM: 127.0.0.1 , TO: www.google.com , FILES: "extracted file: word/document.xml","1.txt","post-data" , RULE: none , ACTION: pass
